version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: cimg/python:3.9.5
    steps:
        - attach_workspace:
           at: .
        - run:
           command: sudo apt-get update
        - run:
           command: apt-get install -y gcc python-dev libkrb5-dev
        - run:
           command: apt-get install python3-pip -y
        - run:
           command: pip3 install --upgrade pip
        - run:
           command: pip3 install --upgrade virtualenv
        - run:
           command: pip3 install pywinrm[kerberos]
        - run:
           command: apt install krb5-user -y
        - run:
           command: pip3 install pywinrm
        - run:
           command: pip3 install ansible
        - run:
           command: ansible-playbook ../ansible/ec2_deploy.yml
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy
         #requires:
          #  - build
         #filters:
         #   branches:
         #      only: master