version: 2.1
jobs:
  build:
    docker:
    - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      #- attach_workspace:
      #   at: .
      - run:
         command: pwd
      - run:
         command: ls
      - run:
      #   command: echo "$VAULT_PWD" > secret.txt
         command: echo devopsvaultpass > secret.txt
      - run:
         command: cat secret.txt
      - run:
         command: pip3 install ansible boto boto3
      - run:
         command: ansible-playbook ./ansible/ec2_deploy.yml --vault-password-file secret.txt
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy
         #requires:
          #  - build
         #filters:
         #   branches:
         #      only: master